'use client';
import {useState,type FormEvent} from 'react';
import {ArrowRight,ArrowUpRight,Eye,EyeOff,LockKeyhole,UserRound,Coffee} from 'lucide-react';
import {Brand} from './brand';
import {api} from '@/lib/client';
export function Login(){
  const [visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);try{await api('/api/auth/login','POST',{username:form.get('username'),password:form.get('password')});window.location.assign('/admin')}catch(e){setError((e as Error).message);setBusy(false)}}
  return <main className="login-page signature-login"><section className="login-visual"><img className="login-photo" src="/coffee-hero.webp" alt="Café latte en una taza de cerámica oscura" fetchPriority="high"/><div className="login-shade"/><div className="visual-top"><Brand light/><span className="small-caps">HECHO CON CALMA.<br/>SERVIDO CON AMOR.</span></div><div className="login-brand-stage"><div className="login-emblem-intro"><div className="login-emblem"><div className="login-steam" aria-hidden="true"><i/><i/><i/></div><img src="/logo-large.webp" alt="Emblema de Coffee Drink" width="560" height="560" fetchPriority="high"/><span className="emblem-orbit" aria-hidden="true"/><span className="emblem-orbit second" aria-hidden="true"/></div></div><div className="login-brand-copy"><span className="eyebrow">CAFÉ · HELADOS · POSTRES</span><h1>La esencia de<br/><em>Coffee Drink.</em></h1><p>Tu café. Tu gente. Tu manera de hacer las cosas.</p></div></div><div className="login-embers" aria-hidden="true"><i/><i/><i/><i/><i/></div><div className="visual-bottom"><span>CAFÉ · POSTRES · HELADOS</span><span className="story-line"/><Coffee size={22}/></div></section><section className="login-form-side"><a href="/menu" className="visit-menu">Explorar nuestra carta <ArrowUpRight size={17}/></a><div className="login-card"><div className="login-signature"><span/><span>COFFEE DRINK</span><span/></div><span className="eyebrow">EL CORAZÓN DE TU CAFETERÍA</span><h2>Qué bueno verte <br/>de nuevo.</h2><p>Cada detalle de Coffee Drink empieza contigo.</p><form onSubmit={submit}><label htmlFor="username">Usuario</label><div className="input-icon"><UserRound size={18}/><input id="username" name="username" placeholder="Tu nombre de usuario" autoComplete="username" required maxLength={80} disabled={busy}/></div><div className="password-label"><label htmlFor="password">Contraseña</label><span>Acceso privado</span></div><div className="input-icon"><LockKeyhole size={18}/><input id="password" name="password" type={visible?'text':'password'} placeholder="Ingresa tu contraseña" autoComplete="current-password" required maxLength={256} disabled={busy}/><button type="button" className="icon-button" aria-label={visible?'Ocultar contraseña':'Mostrar contraseña'} aria-pressed={visible} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{error&&<p className="error-banner" role="alert">{error}</p>}<button className="button primary login-submit" disabled={busy}>{busy?'Ingresando…':'Entrar a mi cafetería'}<ArrowRight size={18}/></button></form><div className="login-security"><LockKeyhole size={13}/><span>Solo para el equipo de Coffee Drink.</span></div></div><footer className="login-footer"><span>© {new Date().getFullYear()} Coffee Drink</span><span>Un pequeño espacio. Grandes momentos.</span></footer></section></main>
}
