'use client';
import {useEffect,useState} from 'react';
import {Check,Copy,Download,ArrowUpRight,QrCode} from 'lucide-react';
import {createQrPoster} from '@/lib/qr-design';
export function QrStudio({qr,url,error}:{qr:string;url:string;error:string}){
  const [poster,setPoster]=useState(''),[designError,setDesignError]=useState(''),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState(''),[preview,setPreview]=useState<'design'|'qr'>('design');
  useEffect(()=>{if(!qr)return;let cancelled=false,objectUrl='';setPoster('');setDesignError('');createQrPoster(qr).then(blob=>{if(cancelled)return;objectUrl=URL.createObjectURL(blob);setPoster(objectUrl)}).catch(e=>{if(!cancelled)setDesignError((e as Error).message)});return()=>{cancelled=true;if(objectUrl)URL.revokeObjectURL(objectUrl)}},[qr]);
  const local=(()=>{try{return ['localhost','127.0.0.1','::1','[::1]'].includes(new URL(url).hostname)}catch{return false}})();
  return <div className="qr-studio"><div className="qr-preview-column"><div className="qr-preview-tabs" aria-label="Vista previa"><button aria-pressed={preview==='design'} onClick={()=>setPreview('design')}>Con diseño</button><button aria-pressed={preview==='qr'} onClick={()=>setPreview('qr')}>Solo QR</button></div><div className={`qr-poster-preview ${preview==='qr'?'plain':''}`} aria-busy={preview==='design'&&!poster&&!designError}>{preview==='design'?(poster?<img src={poster} alt="Diseño imprimible de Coffee Drink con logo, fondo cobre y código QR de la carta" width="1600" height="2400"/>:<div className="qr-preparing" role="status"><QrCode size={35}/><p>{designError||error||'Preparando tu diseño…'}</p></div>):qr?<img src={qr} alt="Código QR de la carta, sin diseño" width="1000" height="1000"/>:<p role="status">Generando QR…</p>}</div></div><div className="qr-details"><span className="eyebrow">DE COFFEE DRINK A CADA MESA</span><h3>Un escaneo.<br/>Tu próxima pausa.</h3><p>Cada cambio de tu carta aparece en el mismo enlace. Puedes seguir usando tu QR mientras mantengas la dirección del negocio.</p><label className="qr-url-label">Enlace para tus clientes<input readOnly value={url} onFocus={e=>e.currentTarget.select()}/></label><div className="qr-tool-row"><button className="button outline" disabled={!url} onClick={async()=>{try{await navigator.clipboard.writeText(url);setCopied(true);setCopyError('')}catch{setCopyError('Selecciona el enlace de arriba para copiarlo.')}}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Enlace copiado':'Copiar enlace'}</button>{url&&<a className="button outline" href={url} target="_blank" rel="noreferrer">Ver carta<ArrowUpRight size={16}/></a>}</div><div className="qr-downloads">{poster?<a className="button primary" href={poster} download="coffee-drink-diseno-qr.png"><Download size={17}/>Descargar diseño completo</a>:<button className="button primary" disabled><Download size={17}/>{designError?'Diseño no disponible':'Preparando diseño…'}</button>}{qr?<a className="button outline" href={qr} download="coffee-drink-solo-qr.png"><QrCode size={17}/>Solo QR</a>:<button className="button outline" disabled>Generando QR…</button>}</div><div className="qr-print-note"><strong>Hecho para tu cafetería</strong><p>Diseño en PNG de 1600 × 2400 píxeles, con el logo original y los colores de Coffee Drink. Ideal para tus mesas o mostrador.</p><small>Solo QR: PNG de 1000 × 1000 píxeles. Conserva su margen blanco al imprimir.</small></div>{local&&<p className="qr-local-note">Estás en la vista local. Para imprimir un QR que tus clientes puedan abrir, descárgalo desde el dominio público una vez publicado.</p>}{(error||designError||copyError)&&<p className="error-banner" role="alert">{error||designError||copyError}</p>}</div></div>
}
